name: michael.cummins
favicon: null
layout_spectrum: 0.69341
typography_spectrum: 0.55045
title: Michael Cummins explores thegrid.ai
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74889772-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4feff'
    - '#00000c'
    - '#444d52'
    - '#778890'
    - '#dc0100'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
