name: michael.cummins
favicon: null
layout_spectrum: 0.68854
typography_spectrum: 0.56024
title: Michael Cummins explores thegrid.ai
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74889772-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#010008'
    - '#e09d06'
    - '#737a73'
    - '#3cd3fe'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
