name: michael.cummins
favicon: null
layout_spectrum: 0.90105
typography_spectrum: 0.65256
title: Michael Cummins on thegrid.ai
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#010008'
    - '#e09d06'
    - '#737a73'
    - '#3cd3fe'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
